{{- range .Values.microservices }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  generation: 1
  name: {{ . | quote }}

spec:
  ingressClassName: nginx
  rules:
  - host: {{ printf "kubernetes.%s.com" . }}
    http:
      paths:
      - backend:
          service:
            name: {{ . | quote }}
            port:
              number: 80
        path: /
        pathType: Exact
---
{{- end }}