{{- range .Values.microservices }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ . | quote }}
    app.kubernetes.io/managed-by: Helm
  name: {{ . | quote }}

spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ . | quote }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
{{- end }}